name: shurligrpc
description: Shurli gRPC client and server.
homepage: https://github.com/Meshbits/shurli-server

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  async: ^2.2.0
  grpc: ^2.2.0
  protobuf: ^1.0.1
